# Dependencies
markdown:         kramdown
highlihts:	      pygments

# Permalinks
permalink:        pretty

# Setup
title:            Thomas Pagram
tagline:          'Full-stack Web Developer'
description:      'Full-stack web developer. <br/>
                    Studied mathematics. <br/>
                    Working at <a href="https://www.airtasker.com/">Airtasker</a>.'
url:              http://tpagram.github.io

google_analytics: UA-100035749-1
author:
  name:           'Thomas Pagram'
  url:            http://tpagram.github.io


# Custom vars
version:          2.0.0

github:           https://github.com/tpagram
linkedin:         https://www.linkedin.com/in/tpagram/

social:
  name: Thomas Pagram
  links:
    - https://github.com/tpagram
    - https://www.linkedin.com/in/tpagram/

logo: /assets/me_circle.png

paginate: 5
paginate_path: "page:num"

plugins:
  - jekyll-seo-tag
  - jekyll-paginate
