# Dependencies
markdown:         kramdown
highlihts:	      pygments

# Permalinks
permalink:        pretty

# Setup
title:            Thomas Pagram
tagline:          'Full-stack Web Developer'
description:      'Full-stack web developer. <br/>
                    Studied mathematics. <br/>
                    Working at <a href="http://www.sentia.com.au">Sentia</a>.'
url:              http://tpagram.github.io

google_analytics: UA-100035749-1
author:
  name:           'Thomas Pagram'
  url:            https://twitter.com/mdo


# Custom vars
version:          2.0.0

github:           https://github.com/tpagram
linkedin:         https://www.linkedin.com/in/tpagram/

gems: [jekyll-paginate]
paginate: 5
paginate_path: "page:num"
